//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _42_LTUDDN_TranQuangQuang_21103100304_DHTI15A5HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.LichHens = new HashSet<LichHen>();
        }
        [Key] 
        public int MaBN { get; set; }
        [Required]
        [Range(5,15)]
        public string HoTen { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        public string GioiTinh { get; set; }
        [Required]
        [Range (10,12)]
        public string SDT_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHen> LichHens { get; set; }
    }
}
