//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _42_LTUDDN_TranQuangQuang_21103100304_DHTI15A5HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.CompilerServices;

    public partial class LichHen
    {
        [Column(Order = 0)]
        public int MaLichHen { get; set; }
        [Column(Order =1)]
        public int MaBN { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> NgayHen_ { get; set; }
        [Required]
        [Range(5,50)]
        public string BacSi_{ get; set; }
        [Required]
        public string LyDo_ { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
